// Dow Jones Industrial Average — 30 components (DIA ETF universe)
export const DJIA_SYMBOLS = [
  "AAPL","AMGN","AMZN","AXP","BA","CAT","CRM","CSCO","CVX","DIS",
  "DOW","GS","HD","HON","IBM","JNJ","JPM","KO","MCD","MRK",
  "MSFT","NKE","NVDA","PG","SHW","TRV","UNH","V","VZ","WMT",
]

// S&P 500 symbols — used as the universe for the screener
export const SP500_SYMBOLS = [
  "AAPL","MSFT","NVDA","AMZN","META","GOOGL","GOOG","BRK.B","LLY","AVGO",
  "JPM","TSLA","UNH","XOM","V","MA","COST","HD","JNJ","PG",
  "ABBV","NFLX","BAC","CRM","WMT","CVX","MRK","ORCL","ADBE","KO",
  "AMD","WFC","PEP","TMO","ACN","LIN","MCD","PM","IBM","ABT",
  "CSCO","DHR","GE","CAT","INTU","ISRG","TXN","AMGN","SPGI","GS",
  "QCOM","RTX","NEE","VZ","HON","BLK","T","LOW","SYK","BKNG",
  "MS","AMAT","AXP","PLD","ELV","GILD","UNP","BMY","DE","LRCX",
  "MDT","VRTX","PGR","REGN","ADI","ETN","SCHW","CB","MU","C",
  "CI","TJX","SO","SBUX","MMC","SHW","KLAC","DUK","CL","CME",
  "EOG","BDX","ZTS","ICE","MCO","APH","NOC","PH","ITW","USB",
  "TGT","FI","HCA","EMR","MAR","COF","FCX","WM","CEG","AON",
  "GD","PSA","MO","NSC","AIG","SRE","AJG","TT","ROP","OKE",
  "ECL","WELL","CCI","AME","F","GM","DLR","EW","FDX","MPC",
  "TDG","AFL","KMB","HLT","CARR","ORLY","PCAR","ALL","ROST","HES",
  "CTAS","NUE","OTIS","PCG","PPG","STZ","JCI","PAYX","MNST","AEP",
  "DVN","APC","HSY","GWW","DOW","DD","VLO","HAL","O","RSG",
  "CHTR","FTNT","IDXX","EXC","ED","WEC","KEYS","XEL","AWK","ES",
  "MTD","ROK","ACGL","FAST","BRO","IR","WST","VRSK","GPN","EFX",
  "CTSH","CINF","CDW","ZBRA","TROW","BALL","MKC","IQV","WAT","FTV",
  "BAX","K","RMD","LHX","ANSS","STE","DLTR","TTWO","WY","DTE",
  "CHD","EIX","ETR","PPL","FE","AES","CMS","D","NI","LNT",
  "PFG","ERIE","NDAQ","CBOE","IEX","BEN","WRB","RJF","LVS","MGM",
  "CZR","WYNN","HIG","GL","PRU","MET","LNC","VOYA","UNM","PNW",
  "NRG","OGE","EVRG","ATO","NFG","SWX","SR","POR","AVA","IDA",
  "HII","L","TXT","SPG","REG","ARE","SLG","VNO","EQR","ESS",
  "MAA","UDR","CPT","NVR","PHM","DHI","LEN","TOL","MDC","MHO",
  "POOL","WSO","MAS","LII","WMS","AWI","CNH","GNRC","TTC","LECO",
  "RBC","BMI","GFF","AOS","WTS","LMT","HWM","TDY","CW","AXON",
  "LDOS","SAIC","BAH","CACI","DRS","PSN","ICFI","MANT","KTOS","HEI",
  "TransDigm","HXL","TGI","VSEC","DY","ATRO","FLIR","SWBI","OLN","SMG",
];
